Library System: C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/BookType.cpp File Reference
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/BookType.cpp File Reference
BookType class implementation
Author: Michael Gell (Student Number: 30276096)
Modified: Thurs 19th May 2011.
.
#include "../h/BookType.h"
#include <fstream>
#include <string>
#include <sstream>
Functions
ostream & operator<< (ostream &os, const BookType &b)
Detailed Description
Definition in file BookType.cpp.
Function Documentation
ostream& operator<< (ostream & os, const BookType & b)
Stream insertion operator override. Arguments: ostream, BookType
Parameters:
os (ostream) The output stream
b (BookType) the book object to insert into the stream.
Returns:
ostream The output stream again.
Writes the data members of this book to the stream, in a nice formatted block of text.
Definition at line 648 of file BookType.cpp.
References BookType::getAuthorAt(), BookType::getIsbn(), BookType::getNumberOfAuthors(), BookType::getNumberOfCopiesInStock(), BookType::getPrice(), BookType::getTitle(), and BookType::title.
{
        // This is basically a "to string" routine.
        string title;
        b.getTitle(title);
        os << "Title:             " << title << endl;
        unsigned authCount;
        b.getNumberOfAuthors(authCount);
        os << "Number of Authors: " << authCount << endl;
        string auth;
        for (unsigned aa = 0; aa < authCount; aa++)
        {
                b.getAuthorAt(auth, aa);
                os << "Author " << aa << ":          " << auth << endl;
        }
        long isb;
        b.getIsbn(isb);
        os << "ISBN:              " << isb << endl;
        unsigned num;
        b.getNumberOfCopiesInStock(num);
        os << "Copies in stock:   " << num << endl;
        double thePrice;
        b.getPrice(thePrice);
        os << "Price:             " << thePrice << endl;
        return os;
}