Library System: BookLoan Class Reference
BookLoan Class Reference
Stores information about a book on loan to a library patron.
#include <BookLoan.h>
Public Member Functions
BookLoan ()
Default Constructor.
.
~BookLoan ()
Destructor.
.
BookLoan (const BookLoan &b)
Copy constructor.
.
const BookLoan & operator= (const BookLoan &otherLoan)
Assignment op override.
.
bool operator== (const BookLoan &otherLoan) const
Equality Comparison operator override.
.
bool operator> (const BookLoan &otherLoan) const
Greater than comparison operator override, uses ISBN.
.
bool operator< (const BookLoan &otherLoan) const
Less than comparison operator override, uses ISBN.
.
void setBookISBN (const long &bIsbn)
Provide the ISBN of the book that is loaned.
.
void setPatronId (const long &l)
Provide the ID of the patron who borrowed the book.
.
void setBorrowedDate (const Date &d)
Set date the book was borrowed.
.
void setDueDate (const Date &d)
Set the date the book is due back.
.
void getBookISBN (long &bIsbn) const
Get the ISBN of the book that is loaned.
.
void getPatronId (long &l) const
Get the ID of the patron who borrowed the book.
.
void getBorrowedDate (Date &d) const
Get date the book was borrowed.
.
void getDueDate (Date &d) const
Get the date the book is due back.
.
long getKey () const
Get the seach key for this object.
.
Private Member Functions
void Reset ()
Reset method.
.
void Copy (const BookLoan &b)
Copy method.
.
Private Attributes
long bookISBN
The ISBN of the book that is on loan.
.
long patronId
The user ID of the patron who borrowed the book.
.
Date borrowedOn
The date that the book was borrowed (or most recently renewed).
.
Date dueOn
The date that the book is due.
.
Detailed Description
Implements Searchable
Definition at line 32 of file BookLoan.h.
Constructor & Destructor Documentation
BookLoan::BookLoan ()
Default Constructor. Arguments: none
Calls Reset() method.
Definition at line 31 of file BookLoan.cpp.
References Reset().
{
        Reset();
}
BookLoan::~BookLoan ()
Destructor. Arguments: none
Definition at line 42 of file BookLoan.cpp.
{
}
BookLoan::BookLoan (const BookLoan & otherLoan)
Copy Constructor. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object we are copying.
Calls Reset and then copies the given loan.
Definition at line 58 of file BookLoan.cpp.
References Copy(), and Reset().
{
        Reset();
        Copy(otherLoan);
}
Member Function Documentation
const BookLoan & BookLoan::operator= (const BookLoan & otherLoan)
Assignment op override. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object we are copying.
Returns:
(BookLoan) The value of the current object (*this)
Copies the given loan object.
Definition at line 77 of file BookLoan.cpp.
References Copy().
{
        // Avoid self-assignment
        if (this != &otherLoan)
        {
                Copy(otherLoan);
        }
        return *this; // The value of the object that was just assigned.
}
bool BookLoan::operator== (const BookLoan & otherLoan) const
Equality comparison operator override.. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object we are comparing to.
Returns:
bool If the loan objects match
Performs member-wise comparison.
Definition at line 103 of file BookLoan.cpp.
References getBookISBN(), getBorrowedDate(), getDueDate(), and getPatronId().
{
        // Checking against self ?
        // This is an address comparison (i think)  OTHERWISE it will be infinite recursion.  AAA!
        if (this != &otherLoan)
        {
                // This BookLoan
                long myBookISBN;
                long myPatronId;
                Date myBorrowedOn;
                Date myDueOn;
                // Get data members.
                getBookISBN    ( myBookISBN);
                getPatronId    ( myPatronId);
                getBorrowedDate( myBorrowedOn);
                getDueDate     ( myDueOn);
                // Other BookLoan
                long otherBookISBN;
                long otherPatronId;
                Date otherBorrowedOn;
                Date otherDueOn;
                // Get data members.
                otherLoan.getBookISBN    ( otherBookISBN);
                otherLoan.getPatronId    ( otherPatronId);
                otherLoan.getBorrowedDate( otherBorrowedOn);
                otherLoan.getDueDate     ( otherDueOn);
                // Equality comparison happens here.
                if      (
                                myBookISBN              == otherBookISBN        &&
                                myPatronId              == otherPatronId        &&
                                myBorrowedOn    == otherBorrowedOn      &&
                                myDueOn                 == otherDueOn
                        )
                {
                        return true;    // Everything matches exactly. Equal.
                }
                return false;           // Members do not match exactly.  Inequal.
        }
        else
        {
                return true; // this == this.  So they are equal.
        }
}
bool BookLoan::operator> (const BookLoan & otherLoan) const
Greater than comparison operator override, uses ISBN.. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object that we are comparing to.
Returns:
bool True if the given loan is less than this loan object.
Compares the loans by their ISBN.
Definition at line 170 of file BookLoan.cpp.
References getBookISBN().
{
        long myISBN;
        long otherISBN;
        // Compare by ISBN
        getBookISBN(myISBN);
        otherLoan.getBookISBN(otherISBN);
        if (myISBN > otherISBN)
        {
                return true;
        }
        return false;
}
bool BookLoan::operator< (const BookLoan & otherLoan) const
Less than comparison operator override, uses ISBN. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object we are comparing to.
Returns:
bool True if the given loan is greater than this loan object.
Compares the loans by their ISBN.
Definition at line 200 of file BookLoan.cpp.
References getBookISBN().
{
        long myISBN;
        long otherISBN;
        // Compare by ISBN
        getBookISBN(myISBN);
        otherLoan.getBookISBN(otherISBN);
        if (myISBN < otherISBN)
        {
                return true;
        }
        return false;
}
void BookLoan::setBookISBN (const long & bIsbn)
Provide the ISBN for the book object that this loan concerns. Arguments: long
Parameters:
bIsbn (long) The ISBN value we are setting with.
Definition at line 231 of file BookLoan.cpp.
References bookISBN.
Referenced by Copy(), LoansLoader::LoadLoans(), and LibSystem::promptBorrowBook().
{
        bookISBN = bIsbn;
}
void BookLoan::setPatronId (const long & l)
Provide the User ID of the patron who this loan concerns. Arguments: long
Parameters:
l (long) the ID of the patron.
Definition at line 245 of file BookLoan.cpp.
References patronId.
Referenced by Copy(), LoansLoader::LoadLoans(), and LibSystem::promptBorrowBook().
{
        patronId = l;
}
void BookLoan::setBorrowedDate (const Date & d)
Set the date of borrowing. Arguments: Date
Parameters:
d (Date) The date the book was borrowed.
Definition at line 257 of file BookLoan.cpp.
References borrowedOn.
Referenced by Copy(), LoansLoader::LoadLoans(), LibSystem::promptBorrowBook(), and LibSystem::renewBookLoan().
{
        borrowedOn = d;
}
void BookLoan::setDueDate (const Date & d)
Set the date that the book is due back. Arguments: Date
Parameters:
d (Date) The date the book is due.
Definition at line 269 of file BookLoan.cpp.
References dueOn.
Referenced by Copy(), LoansLoader::LoadLoans(), LibSystem::promptBorrowBook(), and LibSystem::renewBookLoan().
{
        dueOn = d;
}
void BookLoan::getBookISBN (long & bIsbn) const
Get the ISBN of the book that is on loan. Arguments: long
Parameters:
bIsbn (long) The ISBN
Definition at line 285 of file BookLoan.cpp.
References bookISBN.
Referenced by Copy(), LibSystem::displayLoanDetails(), getKey(), operator<(), operator==(), operator>(), LibSystem::promptReturnBook(), LibSystem::renewBook(), LibSystem::renewBookLoan(), LoansLoader::SaveLoans(), and LibSystem::showLoansForCurrentUser().
{
        bIsbn = bookISBN;
}
void BookLoan::getPatronId (long & l) const
Get the ID of the patron that borrowed the book. Arguments: long
Parameters:
l (long) the User ID of the patron
Definition at line 297 of file BookLoan.cpp.
References patronId.
Referenced by Copy(), LibSystem::displayLoanDetails(), operator==(), LibSystem::promptReturnBook(), LibSystem::renewBook(), LoansLoader::SaveLoans(), and LibSystem::showLoansForCurrentUser().
{
        l = patronId;
}
void BookLoan::getBorrowedDate (Date & d) const
Get the date that the book was borrowed. Arguments: Date
Parameters:
d (Date) The date that the book was borrowed.
Definition at line 309 of file BookLoan.cpp.
References borrowedOn.
Referenced by Copy(), LibSystem::displayLoanDetails(), operator==(), and LoansLoader::SaveLoans().
{
        d = borrowedOn;
}
void BookLoan::getDueDate (Date & d) const
Get the date that the book is due. Arguments: Date
Parameters:
d (Date) The date that the book is due.
Definition at line 321 of file BookLoan.cpp.
References dueOn.
Referenced by Copy(), LibSystem::displayLoanDetails(), operator==(), and LoansLoader::SaveLoans().
{
        d = dueOn;
}
long BookLoan::getKey () const [virtual]
Get the search key for this searchable object. Arguments: none.
Returns:
(long) The key used to search for this object in a Binary Search Tree or other special data structure.
This method is provided so that this class may implement the Searchable interface.
Implements Searchable.
Definition at line 339 of file BookLoan.cpp.
References getBookISBN().
{
        long theKey;
        getBookISBN(theKey);
        return theKey;
}
void BookLoan::Reset () [private]
Reset method. Reset this loan object to default parameters. Arguments: none.
Resets all data members.
Definition at line 354 of file BookLoan.cpp.
References bookISBN, borrowedOn, dueOn, patronId, and Date::Reset().
Referenced by BookLoan().
{
        bookISBN        = 0;    // Not a legal ISBN
        patronId    = 0;        // This is the user ID of a patron who cannot use the system.
        borrowedOn.Reset();
        dueOn.Reset();
}
void BookLoan::Copy (const BookLoan & otherLoan) [private]
Copy method. Arguments: BookLoan
Parameters:
otherLoan (BookLoan) The loan object we are copying from.
Performs a member-wise copy.
Definition at line 372 of file BookLoan.cpp.
References getBookISBN(), getBorrowedDate(), getDueDate(), getPatronId(), setBookISBN(), setBorrowedDate(), setDueDate(), and setPatronId().
Referenced by BookLoan(), and operator=().
{
        // Data to get
        long otherIsbn;
        long otherPatronId;
        Date otherBorrowedDate;
        Date otherDueDate;
        // Get the data from the other object.
        otherLoan.getBookISBN    ( otherIsbn          );
        otherLoan.getPatronId    ( otherPatronId     );
        otherLoan.getBorrowedDate( otherBorrowedDate );
        otherLoan.getDueDate     ( otherDueDate      );
        // Set my data
        setBookISBN     (otherIsbn                      );
        setPatronId     (otherPatronId          );
        setBorrowedDate (otherBorrowedDate      );
        setDueDate      (otherDueDate           );
}
Member Data Documentation
long BookLoan::bookISBN [private]
Definition at line 160 of file BookLoan.h.
Referenced by getBookISBN(), Reset(), and setBookISBN().
long BookLoan::patronId [private]
Definition at line 164 of file BookLoan.h.
Referenced by getPatronId(), Reset(), and setPatronId().
Date BookLoan::borrowedOn [private]
Definition at line 168 of file BookLoan.h.
Referenced by getBorrowedDate(), Reset(), and setBorrowedDate().
Date BookLoan::dueOn [private]
Definition at line 172 of file BookLoan.h.
Referenced by getDueDate(), Reset(), and setDueDate().
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/BookLoan.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/BookLoan.cpp