Library System: Date Class Reference
Date Class Reference
Stores dd mm yyyy (all unsigned int values).
#include <Date.h>
Public Member Functions
Date ()
Default Constructor
.
~Date ()
Destructor
.
void Reset ()
Reset (empty) this object
.
Date (const Date &d)
Copy Constructor
.
const Date & operator= (const Date &rightDate)
Override for the assignment operator
.
bool operator== (const Date &rightDate) const
Override for the equality comparison operator
.
bool SetDayOfMonth (const unsigned &dd)
Set the day of the month (1 - 31)
.
bool SetMonth (const unsigned &mm)
Set the month (1 - 12)
.
void SetYear (const unsigned &yyyy)
Set the year
.
void GetDayOfMonth (unsigned &dd) const
Get the day of the month (1 - 31)
.
void GetMonth (unsigned &mm) const
Get the month (1 - 12)
.
void GetMonthStr (string &monthStr) const
Get the month as a string (January - December)
.
void GetYear (unsigned &yyyy) const
Get the year
.
Private Member Functions
bool DayIsValid () const
Check if the day of the month is valid for the given month
.
Private Attributes
unsigned dayOfMonth
The day of the month
.
unsigned month
The month
.
unsigned year
The year
.
Detailed Description
Stores the date, eg: 31 December 2011
Valid ranges are enforced by mutator methods, eg: November has 30 days.
Definition at line 25 of file Date.h.
Constructor & Destructor Documentation
Date::Date ()
Default Constructor.
Definition at line 25 of file Date.cpp.
References Reset().
{
        Reset();
}
Date::~Date ()
Destructor.
Definition at line 45 of file Date.cpp.
{
}
Date::Date (const Date & d)
Copy Constructor. Argument: Date
Parameters:
d Date instance whose properties we are copying from.
Definition at line 34 of file Date.cpp.
References dayOfMonth, GetDayOfMonth(), GetMonth(), GetYear(), month, and year.
{
        d.GetDayOfMonth(dayOfMonth);
        d.GetMonth(month);
        d.GetYear(year);
}
Member Function Documentation
void Date::Reset ()
Reset (empty) this object.
Definition at line 51 of file Date.cpp.
References dayOfMonth, month, and year.
Referenced by Date(), and BookLoan::Reset().
{
        // Reset member variables.
        dayOfMonth = 1;
        month      = 1;
        year       = 2000;
}
const Date & Date::operator= (const Date & rightDate)
Overrides the Assignment Operator. Argument: Date
Parameters:
rightDate The Date instance whose properties we are deep-copying from.
Returns:
The value of the object just assigned, eg: *this
Definition at line 283 of file Date.cpp.
References GetDayOfMonth(), GetMonth(), GetYear(), SetDayOfMonth(), SetMonth(), and SetYear().
{
        // Avoid self-assignment
        if (this != &rightDate)
        {
                unsigned dom, mon, yr;
                rightDate.GetDayOfMonth(dom);
                rightDate.GetMonth(mon);
                rightDate.GetYear(yr);
                SetDayOfMonth(dom);
                SetMonth(mon);
                SetYear(yr);
        }
        return *this; // The value of the object that was just assigned.
}
bool Date::operator== (const Date & rightDate) const
Overrides the Equality Comparison Operator. Argument: Date
Parameters:
rightDate The Date instance whose values we are comparing against.
Returns:
bool true if these Date objects are equal.
Definition at line 307 of file Date.cpp.
References GetDayOfMonth(), GetMonth(), and GetYear().
{
        unsigned dom, mon, yr;
        rightDate.GetDayOfMonth(dom);
        rightDate.GetMonth(mon);
        rightDate.GetYear(yr);
        unsigned myDom, myMon, myYr;
        GetDayOfMonth(myDom);
        GetMonth(myMon);
        GetYear(myYr);
        if (
                dom == myDom &&
                mon == myMon &&
                 yr == myYr
                )
        {
                return true;
        }
        return false;
}
bool Date::SetDayOfMonth (const unsigned & dd)
Set the day of the month. Argument: unsigned
Parameters:
dd The day of the month, eg 1 - 31.
If an invalid day is specified (eg 32) then this method will have no effect and will return false.
Returns:
true if successful.
Definition at line 118 of file Date.cpp.
References DayIsValid(), and dayOfMonth.
Referenced by LoansLoader::LoadLoans(), operator=(), and LibSystem::setToToday().
{
        // Keep a backup in case this method fails.
        unsigned oldDay = dayOfMonth;
        dayOfMonth = dd;
        // Check validity.
        if (DayIsValid())
        {
                // Success.
                return true;
        }
        // Unsuccessful.
        dayOfMonth = oldDay; // Revert back to previous value.
        return false;
}
bool Date::SetMonth (const unsigned & mm)
Set the month. Argument: unsigned
Parameters:
mm The month, eg 1 - 12.
If the current value for the day of the month is not valid with the given month,
(eg, 31 November) then this method will have no effect and will return false.
Returns:
true if successful.
Definition at line 149 of file Date.cpp.
References DayIsValid(), and month.
Referenced by LoansLoader::LoadLoans(), operator=(), LibSystem::promptBorrowBook(), LibSystem::renewBookLoan(), and LibSystem::setToToday().
{
        if (mm <= 12 && mm > 0)
        {
                // Keep a backup in case this method fails.
                unsigned oldMonth = month;
                month = mm;
                // Check validity.
                if (DayIsValid())
                {
                        // Success.
                        return true;
                }
                // Unsuccessful.
                month = oldMonth; // Revert back to previous value.
        }
        return false;
}
void Date::SetYear (const unsigned & yyyy)
Set the year. Argument: unsigned
Parameters:
yyyy The year, eg 2011.
Definition at line 177 of file Date.cpp.
References year.
Referenced by LoansLoader::LoadLoans(), operator=(), and LibSystem::setToToday().
{
        year = yyyy;
}
void Date::GetDayOfMonth (unsigned & dd) const
Get the day of the month. Argument: unsigned
Parameters:
dd (reference parameter) receives the value of the day of the month.
Definition at line 192 of file Date.cpp.
References dayOfMonth.
Referenced by Date(), LibSystem::displayDate(), operator=(), operator==(), and LoansLoader::SaveLoans().
{
        dd = dayOfMonth;
}
void Date::GetMonth (unsigned & mm) const
Get the month. Argument: unsigned
Parameters:
mm (reference parameter) receives the value of the month.
Definition at line 201 of file Date.cpp.
References month.
Referenced by Date(), operator=(), operator==(), LibSystem::promptBorrowBook(), LibSystem::renewBookLoan(), and LoansLoader::SaveLoans().
{
        mm = month;
}
void Date::GetMonthStr (string & monthStr) const
Get the month as a string. Argument: string
Parameters:
monthStr (reference parameter) receives the value of the month as a descriptive string.
Definition at line 209 of file Date.cpp.
References month.
Referenced by LibSystem::displayDate().
{
        switch(month)
        {
                case 1:
                monthStr = "January";
                break;
                case 2:
                monthStr = "February";
                break;
                case 3:
                monthStr = "March";
                break;
                case 4:
                monthStr = "April";
                break;
                case 5:
                monthStr = "May";
                break;
                case 6:
                monthStr = "June";
                break;
                case 7:
                monthStr = "July";
                break;
                case 8:
                monthStr = "August";
                break;
                case 9:
                monthStr = "September";
                break;
                case 10:
                monthStr = "October";
                break;
                case 11:
                monthStr = "November";
                break;
                case 12:
                monthStr = "December";
                break;
        }
}
void Date::GetYear (unsigned & yyyy) const
Get the year. Argument: unsigned
Parameters:
yyyy (reference parameter) receives the value of the year.
Definition at line 269 of file Date.cpp.
References year.
Referenced by Date(), LibSystem::displayDate(), operator=(), operator==(), and LoansLoader::SaveLoans().
{
        yyyy = year;
}
bool Date::DayIsValid () const [private]
Checks if the (dayOfMonth) is valid for the (month).
Returns:
true if valid.
Definition at line 65 of file Date.cpp.
References month.
Referenced by SetDayOfMonth(), and SetMonth().
{
        unsigned monMax = 31;
        switch(month)
        {
                case 2:
                //"February"
                // Assumes we are not on a leap year.
                // There is room for improvement here.
                monMax = 28;
                break;
                case 4:
                //"April"
                monMax = 30;
                break;
                case 6:
                //"June"
                monMax = 30;
                break;
                case 9:
                //"September"
                monMax = 30;
                break;
                case 11:
                //"November"
                monMax = 30;
                break;
        }
        // Enforce a valid range for the day of the month.
        if (dayOfMonth <= monMax && dayOfMonth > 0)
        {
                return true;
        }
        return false;
}
Member Data Documentation
unsigned Date::dayOfMonth [private]
Definition at line 125 of file Date.h.
Referenced by Date(), GetDayOfMonth(), Reset(), and SetDayOfMonth().
unsigned Date::month [private]
Definition at line 129 of file Date.h.
Referenced by Date(), DayIsValid(), GetMonth(), GetMonthStr(), Reset(), and SetMonth().
unsigned Date::year [private]
Definition at line 133 of file Date.h.
Referenced by Date(), GetYear(), Reset(), and SetYear().
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/Date.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/Date.cpp