Library System: BookType Class Reference
BookType Class Reference
Stores information about a book in the library system.
#include <BookType.h>
Public Member Functions
BookType (const BookType &b)
Copy constructor.
.
const BookType & operator= (const BookType &otherBook)
Assignment op override.
.
bool operator== (const BookType &otherBook) const
Equality op override.
.
bool operator> (const BookType &otherBook) const
Greater than comparison operator override.
.
bool operator< (const BookType &otherBook) const
Less than comparison operator override.
.
~BookType ()
Destructor.
.
BookType ()
Constructor (default).
.
void setTitle (const string &t)
Set the title of the book.
.
void setPublisher (const string &p)
Set the publisher of the book.
.
void setIsbn (const long &l)
Set the ISBN of the book.
.
void setPrice (const double &p)
Set the price of the book.
.
void setNumberOfCopiesInStock (const unsigned &n)
Set the number of copies of the book that are owned by the library.
.
void setNumberOfAuthors (const unsigned &n)
Set the number of authors of the book.
.
void getTitle (string &t) const
Get the title of the book.
.
void getPublisher (string &p) const
Get the publisher of the book.
.
void getIsbn (long &l) const
Get the ISBN of the book.
.
void getPrice (double &p) const
Get the price of the book.
.
void getNumberOfCopiesInStock (unsigned &n) const
Get the number of copies of the book that are owned by the library.
.
void getNumberOfAuthors (unsigned &n) const
Get the number of authors of the book.
.
void setAuthorAt (const string &a, const unsigned &idx)
Set the author at the given index.
.
void getAuthorAt (string &a, const unsigned &idx) const
Get the author at the given index.
.
void toString (string &ss) const
Produce a string from this book's data members.
.
long getKey () const
Get the search key of this searchable object.
.
Private Member Functions
void Reset ()
Reset this book to its default data member settings.
.
void clearAuthors ()
Deallocates and sets authors = 0 (NULL).
.
void Copy (const BookType &b)
Copy method.
.
Private Attributes
string title
The title of the book.
.
string * authors
Points to the first item in a dynamically allocated array of strings, containing the (full) name(s) of the author(s).
.
string publisher
The publisher of the book.
.
long isbn
The ISBN of the book.
.
double price
The price of the book.
.
unsigned numberOfCopiesInStock
The number of copies of the book that are owned by the library.
.
unsigned numberOfAuthors
The number of authors of this book.
.
Friends
ostream & operator<< (ostream &os, const BookType &b)
Stream insertion operator override.
.
Detailed Description
Implements Searchable
Definition at line 29 of file BookType.h.
Constructor & Destructor Documentation
BookType::BookType (const BookType & otherBook)
Copy Constructor. Arguments: BookType
Parameters:
otherBook (BookType) The book that we are copying from.
Resets this book to defaults, and then copies data into it.
Definition at line 75 of file BookType.cpp.
References authors, Copy(), and Reset().
{
        authors = 0;
        //cout << " (BookType) (Copy Constructor) authors = 0" << endl;
        //cout << " otherBook: " << endl << otherBook << endl;
        Reset();
        Copy(otherBook);
}
BookType::~BookType ()
Destructor. Arguments: none.
Deallocates dynamic memory.
Definition at line 256 of file BookType.cpp.
References clearAuthors().
{
        //cout << " (BookType) Destructor() " << endl;
        clearAuthors(); // deallocates and sets authors = 0;
}
BookType::BookType ()
Constructor (default). Arguments: none.
Calls Reset() method.
Definition at line 272 of file BookType.cpp.
References authors, and Reset().
{
        //cout << " (BookType) Constructor (default) authors = 0" << endl;
        authors = 0;
        Reset();
}
Member Function Documentation
const BookType & BookType::operator= (const BookType & otherBook)
Assignment Operator override.. Arguments: BookType
Parameters:
otherBook (BookType) The book object that we are copying from.
Returns:
BookType The value of this object (*this)
Checks for self-assignment first.
Definition at line 98 of file BookType.cpp.
References Copy().
{
        // Avoid self-assignment
        if (this != &otherBook)
        {
                Copy(otherBook);
        }
        return *this; // The value of the object that was just assigned.
}
bool BookType::operator== (const BookType & otherBook) const
Equality comparison operator override.. Arguments: BookType
Parameters:
otherBook (BookType) The book object that we are comparing against.
Returns:
bool Returns true if the two book objects are equal.
Performs member-wise comparison for equality.
Definition at line 169 of file BookType.cpp.
References getAuthorAt(), getIsbn(), getNumberOfAuthors(), getNumberOfCopiesInStock(), getPrice(), getPublisher(), and getTitle().
{
        // Checking against self ?
        // This is an address comparison (i think)  OTHERWISE it will be infinite recursion.  AAA!
        if (this != &otherBook)
        {
                // Get the data from this object.
                // Local variables
                string   volumeTitle;
                string   volumePublisher;
                long     volumeIsbn;
                double   volumePrice;
                unsigned volumeCopies;
                unsigned volumeAuthCount;
                getTitle                 ( volumeTitle     );
                getPublisher             ( volumePublisher );
                getIsbn                  ( volumeIsbn      );
                getPrice                 ( volumePrice     );
                getNumberOfCopiesInStock ( volumeCopies    );
                getNumberOfAuthors       ( volumeAuthCount );
                // Get the data from the object we are comparing to.
                // Local variables
                string   volumeTitleOther;
                string   volumePublisherOther;
                long     volumeIsbnOther;
                double   volumePriceOther;
                unsigned volumeCopiesOther;
                unsigned volumeAuthCountOther;
                otherBook.getTitle                 ( volumeTitleOther     );
                otherBook.getPublisher             ( volumePublisherOther );
                otherBook.getIsbn                  ( volumeIsbnOther      );
                otherBook.getPrice                 ( volumePriceOther     );
                otherBook.getNumberOfCopiesInStock ( volumeCopiesOther    );
                otherBook.getNumberOfAuthors       ( volumeAuthCountOther );
                // Equality comparison happens here.
                if      (
                        volumeTitle             == volumeTitleOther             &&
                        volumePublisher == volumePublisherOther &&
                        volumeIsbn              == volumeIsbnOther              &&
                        volumePrice             == volumePriceOther             &&
                        volumeCopies    == volumeCopiesOther    &&
                        volumeAuthCount == volumeAuthCountOther
                        )
                {
                        // All equal so far. Now check each author.
                        // Both have the same number of authors.
                        string auth;
                        string authOther;
                        for(unsigned a = 0; a < volumeAuthCount; a ++)
{
                                getAuthorAt (auth, a);
                                getAuthorAt (authOther, a);
                                if(auth != authOther)
{
                                        return false;  // Authors do not match exactly.  Inequal.
                                }
                        }
                        return true; // Everything matches exactly. Equal.
                }
                return false;  // Members do not match exactly.  Inequal.
        }
        else
        {
                return true; // this == this.  So they are equal.
        }
}
bool BookType::operator> (const BookType & otherBook) const
Greater than comparison operator override.. Arguments: BookType
Parameters:
otherBook (BookType) The book object that we are comparing against.
Returns:
bool Returns true if this book object is greater than the given book object.
Compares by ISBN.
Definition at line 122 of file BookType.cpp.
References getIsbn().
{
        long volumeIsbn;
        long volumeIsbnOther;
        getIsbn ( volumeIsbn      );
        getIsbn ( volumeIsbnOther );
        return (volumeIsbn > volumeIsbnOther);
}
bool BookType::operator< (const BookType & otherBook) const
Less than comparison operator override.. Arguments: BookType
Parameters:
otherBook (BookType) The book object that we are comparing against.
Returns:
bool Returns true if this book object is less than the given book object.
Compares by ISBN.
Definition at line 146 of file BookType.cpp.
References getIsbn().
{
        long volumeIsbn;
        long volumeIsbnOther;
        getIsbn ( volumeIsbn      );
        getIsbn ( volumeIsbnOther );
        return (volumeIsbn < volumeIsbnOther);
}
void BookType::setTitle (const string & t)
Set the book title. Arguments: string
Parameters:
t (string) The title of the book.
Definition at line 328 of file BookType.cpp.
References title.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        title = t;
}
void BookType::setPublisher (const string & p)
Set the book publisher. Arguments: string
Parameters:
p (string) The publisher.
Definition at line 341 of file BookType.cpp.
References publisher.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        publisher = p;
}
void BookType::setIsbn (const long & l)
Set the ISBN of the book. Arguments: long
Parameters:
l (long) The ISBN of the book.
Definition at line 354 of file BookType.cpp.
References isbn.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        isbn = l;
}
void BookType::setPrice (const double & p)
Set the price of the book. Arguments: double
Parameters:
p (double) The price (dollars.cents) of this book.
Definition at line 368 of file BookType.cpp.
References price.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        price = p;
}
void BookType::setNumberOfCopiesInStock (const unsigned & n)
Set the number of copies of this book that the library owns. Arguments: unsigned
Parameters:
n (unsigned) The number of copies the library owns.
Definition at line 381 of file BookType.cpp.
References numberOfCopiesInStock.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        numberOfCopiesInStock = n;
}
void BookType::setNumberOfAuthors (const unsigned & n)
Set the number of authors that this book has. Arguments: unsigned
Parameters:
n (unsigned) The number of authors.
Need to call this before you set any authors. Required for dynamic memory allocation.
Definition at line 395 of file BookType.cpp.
References numberOfAuthors.
Referenced by BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        numberOfAuthors = n;
}
void BookType::getTitle (string & t) const
Get the title of this book. Arguments: string
Parameters:
t (string) Receives the title of this book.
Definition at line 412 of file BookType.cpp.
References title.
Referenced by Copy(), LibSystem::displayBookDetails(), LibSystem::init(), operator<<(), operator==(), LibSystem::printAllVolumes(), BooksLoader::SaveLibraryBooks(), and toString().
{
        t = title;
}
void BookType::getPublisher (string & p) const
Get the publisher of this book.. Arguments: string
Parameters:
p (string) The publisher of this book.
Definition at line 425 of file BookType.cpp.
References publisher.
Referenced by Copy(), LibSystem::displayBookDetails(), operator==(), and BooksLoader::SaveLibraryBooks().
{
        p = publisher;
}
void BookType::getIsbn (long & l) const
Get the ISBN of this book. Arguments: long
Parameters:
l (long) The ISBN of this book
Definition at line 438 of file BookType.cpp.
References isbn.
Referenced by LibSystem::availableCount(), Copy(), LibSystem::displayBookDetails(), getKey(), LibSystem::init(), operator<(), operator<<(), operator==(), operator>(), BooksLoader::SaveLibraryBooks(), and toString().
{
        l = isbn;
}
void BookType::getPrice (double & p) const
Get the price of this book. Arguments: double
Parameters:
p (double) The price of this book
Definition at line 451 of file BookType.cpp.
References price.
Referenced by Copy(), LibSystem::displayBookDetails(), operator<<(), operator==(), BooksLoader::SaveLibraryBooks(), and toString().
{
        p = price;
}
void BookType::getNumberOfCopiesInStock (unsigned & n) const
Get the number of copies of this book that the library owns. Arguments: unsigned
Parameters:
n (unsigned) The number of copies of this book that the library owns
Definition at line 464 of file BookType.cpp.
References numberOfCopiesInStock.
Referenced by Copy(), LibSystem::displayBookDetails(), operator<<(), operator==(), BooksLoader::SaveLibraryBooks(), and toString().
{
        n = numberOfCopiesInStock;
}
void BookType::getNumberOfAuthors (unsigned & n) const
Get the number of authors that this book has. Arguments: unsigned
Parameters:
n (unsigned) The number of authors that this book has
Definition at line 477 of file BookType.cpp.
References numberOfAuthors.
Referenced by Copy(), LibSystem::displayBookDetails(), operator<<(), operator==(), BooksLoader::SaveLibraryBooks(), and toString().
{
        n = numberOfAuthors;
}
void BookType::setAuthorAt (const string & a, const unsigned & idx)
Set the author at the given index. Arguments: string, unsigned
Parameters:
a (string) The (full name) of the author. May include spaces.
idx (unsigned) The index to set. (3 == maximum)
Definition at line 522 of file BookType.cpp.
References authors, and numberOfAuthors.
Referenced by Copy(), BooksLoader::LoadLibraryBooks(), and LibSystem::staffAddBooks().
{
        //cout << "    setAuthorAt() string: " << a << "  idx: " << idx << endl;
        if (idx < numberOfAuthors)
        {
                string s;
                s = a;
                authors[idx] = s;
                //cout << "SET AUTHOR: " << a << endl;
        }
}
void BookType::getAuthorAt (string & theStr, const unsigned & idx) const
Get the author at the given index. Arguments: string, unsigned
Parameters:
theStr (string) The (full name) of the author. May include spaces.
idx (unsigned) The index to get. (3 == maximum)
Definition at line 548 of file BookType.cpp.
References authors, and numberOfAuthors.
Referenced by Copy(), LibSystem::displayBookDetails(), operator<<(), operator==(), BooksLoader::SaveLibraryBooks(), and toString().
{
        if (idx < numberOfAuthors)
        {
                theStr = authors[idx];
        }
}
void BookType::toString (string & outstr) const
Give the data members of this object as a descriptive string. Arguments: string
Parameters:
outstr (string) The string to receive the data.
Definition at line 566 of file BookType.cpp.
References getAuthorAt(), getIsbn(), getNumberOfAuthors(), getNumberOfCopiesInStock(), getPrice(), getTitle(), and title.
{
        string title;
        getTitle(title);
        outstr.append("Title:             ");
        outstr.append(title);
        outstr.append("\n");
        stringstream ss;
        string appStr;
        unsigned authCount;
        getNumberOfAuthors(authCount);
        ss << authCount;
        ss >> appStr;
        outstr.append("Number of Authors: ");
        outstr.append(appStr);
        outstr.append("\n");
        string auth;
        for (unsigned aa = 0; aa < authCount; aa++)
        {
                getAuthorAt(auth, aa);
                ss << aa;
                ss >> appStr;
                outstr.append("Author ");
                outstr.append(appStr);
                outstr.append(":          ");
                ss << auth;
                ss >> appStr;
                outstr.append(appStr);
                outstr.append("\n");
        }
        long isb;
        getIsbn(isb);
        ss << isb;
        ss >> appStr;
        outstr.append("ISBN:              ");
        outstr.append(appStr);
        outstr.append("\n");
        unsigned num;
        getNumberOfCopiesInStock(num);
        outstr.append("Copies in stock:   ");
        ss << num;
        ss >> appStr;
        outstr.append(appStr);
        outstr.append("\n");
        double thePrice;
        getPrice(thePrice);
        outstr.append("Price:             ");
        ss << thePrice;
        ss >> appStr;
        outstr.append(appStr);
        outstr.append("\n");
}
long BookType::getKey () const [virtual]
Get the search key. Arguments: none.
Returns:
long The search key used for searching for this object in special data structures
This method is provided so that this class can implement the Searchable interface.
Implements Searchable.
Definition at line 495 of file BookType.cpp.
References getIsbn().
{
        long theKey;
        getIsbn(theKey);
        return theKey;
}
void BookType::Reset () [private]
Reset method. Arguments: none.
Reets the data members of this book to the default settings.
Definition at line 33 of file BookType.cpp.
References authors, clearAuthors(), isbn, numberOfAuthors, numberOfCopiesInStock, price, publisher, and title.
Referenced by BookType().
{
        //cout << " (BookType) Reset()" << endl;
        clearAuthors(); // sets authors = 0;
        title = "";
        authors = new string [4]; //allocate
        publisher = "";
        isbn = 0;
        price = 0.0;
        numberOfCopiesInStock = 0;
        numberOfAuthors = 0;
}
void BookType::clearAuthors () [private]
Delete authors and deallocate memory. Arguments: none.
Definition at line 55 of file BookType.cpp.
References authors.
Referenced by Copy(), Reset(), and ~BookType().
{
        if (authors != 0)
        {
                //cout << " (BookType) clearAuthors() ... delete [] authors" << endl;
                delete [] authors;
        }
        authors = 0;
}
void BookType::Copy (const BookType & otherBook) [private]
Copy method. Arguments: BookType
Parameters:
otherBook (BookType) The book object that we are copying from.
Copies the data members of the given object into this book object.
Definition at line 292 of file BookType.cpp.
References authors, clearAuthors(), getAuthorAt(), getIsbn(), getNumberOfAuthors(), getNumberOfCopiesInStock(), getPrice(), getPublisher(), getTitle(), isbn, numberOfAuthors, numberOfCopiesInStock, price, publisher, setAuthorAt(), and title.
Referenced by BookType(), and operator=().
{
        //cout << " (BookType) Copy() ..." << endl;
        clearAuthors(); // deallocates and sets authors = 0;
        otherBook.getTitle(title);
        otherBook.getPublisher(publisher);
        otherBook.getIsbn(isbn);
        otherBook.getPrice(price);
        otherBook.getNumberOfCopiesInStock(numberOfCopiesInStock);
        otherBook.getNumberOfAuthors(numberOfAuthors);
        authors = new string [4]; //allocate
        string auth;
        for(unsigned a = 0; a < 4; a++)
        {
                otherBook.getAuthorAt(auth, a);
                //cout << "COPY CONSTRUCTING AUTHOR... " << a << " auth value: " << auth << endl;
                setAuthorAt(auth, a);
        }
}
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const BookType & b) [friend]
Stream insertion operator override. Arguments: ostream, BookType
Parameters:
os (ostream) The output stream
b (BookType) the book object to insert into the stream.
Returns:
ostream The output stream again.
Writes the data members of this book to the stream, in a nice formatted block of text.
Definition at line 648 of file BookType.cpp.
{
        // This is basically a "to string" routine.
        string title;
        b.getTitle(title);
        os << "Title:             " << title << endl;
        unsigned authCount;
        b.getNumberOfAuthors(authCount);
        os << "Number of Authors: " << authCount << endl;
        string auth;
        for (unsigned aa = 0; aa < authCount; aa++)
        {
                b.getAuthorAt(auth, aa);
                os << "Author " << aa << ":          " << auth << endl;
        }
        long isb;
        b.getIsbn(isb);
        os << "ISBN:              " << isb << endl;
        unsigned num;
        b.getNumberOfCopiesInStock(num);
        os << "Copies in stock:   " << num << endl;
        double thePrice;
        b.getPrice(thePrice);
        os << "Price:             " << thePrice << endl;
        return os;
}
Member Data Documentation
string BookType::title [private]
Definition at line 182 of file BookType.h.
Referenced by Copy(), getTitle(), operator<<(), Reset(), setTitle(), and toString().
string* BookType::authors [private]
Definition at line 187 of file BookType.h.
Referenced by BookType(), clearAuthors(), Copy(), getAuthorAt(), Reset(), and setAuthorAt().
string BookType::publisher [private]
Definition at line 192 of file BookType.h.
Referenced by Copy(), getPublisher(), Reset(), and setPublisher().
long BookType::isbn [private]
Definition at line 197 of file BookType.h.
Referenced by Copy(), getIsbn(), Reset(), and setIsbn().
double BookType::price [private]
Definition at line 202 of file BookType.h.
Referenced by Copy(), getPrice(), Reset(), and setPrice().
unsigned BookType::numberOfCopiesInStock [private]
Definition at line 207 of file BookType.h.
Referenced by Copy(), getNumberOfCopiesInStock(), Reset(), and setNumberOfCopiesInStock().
unsigned BookType::numberOfAuthors [private]
Definition at line 212 of file BookType.h.
Referenced by Copy(), getAuthorAt(), getNumberOfAuthors(), Reset(), setAuthorAt(), and setNumberOfAuthors().
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/BookType.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/BookType.cpp