Library System: ReadCsv Class Reference
ReadCsv Class Reference
Read a file of csv data into a 2D vector of strings.
#include <ReadCsv.h>
Public Member Functions
ReadCsv ()
Default Constructor.
.
void Read (std::istream &input, std::vector< std::vector< std::string > > &output)
Read a file of csv data into a 2D vector of strings.
.
Detailed Description
Definition at line 27 of file ReadCsv.h.
Constructor & Destructor Documentation
ReadCsv::ReadCsv ()
Default Constructor. Arguments: none.
Definition at line 32 of file ReadCsv.cpp.
{
}
Member Function Documentation
void ReadCsv::Read (std::istream & input, std::vector< std::vector< std::string > > & output)
Read a text file (containing CSV data). Arguments: istream, vector<vector<string>>
Parameters:
input (istream) The input stream (file) that we are reading from. Must be already open.
output (vector<vector<string>>) A 2D vector of strings to be populated with csv data.
Accepts an open input file stream
Definition at line 47 of file ReadCsv.cpp.
Referenced by BooksLoader::LoadLibraryBooks(), LoansLoader::LoadLoans(), and MembersLoader::LoadUsers().
{
        std::string csvLine;
        // read every line from the stream
        while( std::getline(input, csvLine) )
        {
                std::istringstream csvStream(csvLine);
                std::vector<std::string> csvColumn;
                std::string csvElement;
                // read every element from the line that is seperated by commas
                // and put it into the vector of strings
                while( std::getline(csvStream, csvElement, ',') )
                {
                        csvColumn.push_back(csvElement);
                }
                output.push_back(csvColumn);
        }
}
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/ReadCsv.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/ReadCsv.cpp