Library System: SimpleBinaryTree< T > Class Template Reference
SimpleBinaryTree< T > Class Template Reference
A templated binary tree.
#include <SimpleBinaryTree.h>
Public Member Functions
SimpleBinaryTree ()
Default Constructor.
.
SimpleBinaryTree (const SimpleBinaryTree< T > &otherTree)
Copy Constructor.
.
virtual ~SimpleBinaryTree ()
Virtual Destructor.
.
const SimpleBinaryTree & operator= (const SimpleBinaryTree< T > &otherTree)
Assignment Operator override.
.
bool isEmpty () const
Returns true if the binary tree is empty.
.
void inOrderTraversal () const
Nodes are printed in inorder sequence.
.
void preOrderTraversal () const
Nodes are printed in preorder sequence.
.
void postOrderTraversal () const
Nodes are printed in postorder sequence.
.
int treeHeight () const
Returns the height of the binary tree.
.
int treeNodeCount () const
Returns the number of nodes in the tree.
.
int treeLeavesCount () const
Returns the number of leaves in the tree.
.
void destroyTree ()
Deallocate each node, set root = null.
.
virtual bool searchByKey (const long &searchKey) const =0
Return true if item with the given key is found in the tree.
.
virtual bool search (const T &searchItem) const =0
Return true if item found in tree.
.
virtual void insert (const T &insertItem)=0
Creates a node and inserts in tree, if not causing duplicate.
.
virtual void deleteNode (const T &deleteItem)=0
Delete first node found with same data as deleteItem. If tree is empty or item is not found, print a message.
.
Protected Attributes
nodeType< T > * root
The root node of this tree.
.
Private Member Functions
void copyTree (nodeType< T > *&copiedTreeRoot, nodeType< T > *otherTreeRoot)
Make a copy of the binary tree to which otherTreeRoot points.
.
void destroy (nodeType< T > *&p)
Destroy the binary tree to which p points.
.
void inOrder (nodeType< T > *p) const
Do an in order traversal of the binary tree to which p points, printing each node.
.
void preOrder (nodeType< T > *p) const
Do a pre-order traversal of the binary tree to which p points, printing each node.
.
void postOrder (nodeType< T > *p) const
Do a post-order traversal of the binary tree to which p points, printing each node.
.
int height (nodeType< T > *p) const
Find the height of the tree.
.
int max (const int &x, const int &y) const
Returns the larger of x and y parameters.
.
int nodeCount (nodeType< T > *p) const
Returns the number of nodes in the binary tree to which p points.
.
int leavesCount (nodeType< T > *p) const
Returns the number of leaves in the binary tree to which p points.
.
Detailed Description
template<class T>
class SimpleBinaryTree< T >
Abstract class providing virtual methods for searchByKey(), search(), insert(), deleteNode() ...and the Destructor.
Definition at line 41 of file SimpleBinaryTree.h.
Constructor & Destructor Documentation
template<class T> SimpleBinaryTree< T >::SimpleBinaryTree () [inline]
Default Constructor. Arguments: none
Initialises the root of this tree to NULL.
(Default) constructor.
Definition at line 246 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::root.
{
        root = 0;
}
template<class T> SimpleBinaryTree< T >::SimpleBinaryTree (const SimpleBinaryTree< T > & otherTree) [inline]
Copy Constructor. Arguments: SimpleBinaryTree<T>
Parameters:
otherTree (SimpleBinaryTree<T>) The tree we are copying from.
Copies the given tree into this tree, overwriting all data.
Copy Constructor.
Definition at line 263 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::copyTree(), and SimpleBinaryTree< T >::root.
{
        if (otherTree.root == 0)
                root = 0;
        else
                copyTree(root, otherTree.root);
}
template<class T> SimpleBinaryTree< T >::~SimpleBinaryTree () [inline, virtual]
Virtual Destructor. Arguments: none
Destroys the root of this tree.
Virtual Destructor.
Definition at line 230 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::destroy(), and SimpleBinaryTree< T >::root.
{
        destroy(root);
}
Member Function Documentation
template<class T> const SimpleBinaryTree< T > & SimpleBinaryTree< T >::operator= (const SimpleBinaryTree< T > & otherTree) [inline]
Assignment Operator override. Arguments: SimpleBinaryTree<T>
Parameters:
otherTree (SimpleBinaryTree<T>) The tree we are copying from.
Copies the given tree into this tree, overwriting all data. Returns the value of the current object (*this)
Assignment operator override.
Definition at line 288 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::copyTree(), SimpleBinaryTree< T >::destroy(), and SimpleBinaryTree< T >::root.
{
        // Avoid self-assignment
        if (this != &otherTree)
        {
                if (root != 0)
                        destroy(root);
                if (otherTree.root == 0)
                        root = 0;
                else
                        copyTree(root, otherTree.root);
        }
        return *this; // The value of the object that was just assigned.
}
template<class T> bool SimpleBinaryTree< T >::isEmpty () const [inline]
Find if the tree is empty. Arguments: none
Returns:
(bool) true if the root node is null.
Definition at line 319 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::root.
Referenced by LibSystem::availableCount(), LibSystem::isLoaned(), and LibSystem::printAllVolumes().
{
        return (root == 0);
}
template<class T> void SimpleBinaryTree< T >::inOrderTraversal () const [inline]
Perform an in-order traversal, printing each node. Arguments: none
Definition at line 553 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::inOrder(), and SimpleBinaryTree< T >::root.
{
        inOrder(root);
}
template<class T> void SimpleBinaryTree< T >::preOrderTraversal () const [inline]
Perform a pre-order traversal, printing each node. Arguments: none
Definition at line 564 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::preOrder(), and SimpleBinaryTree< T >::root.
{
        preOrder(root);
}
template<class T> void SimpleBinaryTree< T >::postOrderTraversal () const [inline]
Perform a post-order traversal, printing each node. Arguments: none
Definition at line 576 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::postOrder(), and SimpleBinaryTree< T >::root.
{
        postOrder(root);
}
template<class T> int SimpleBinaryTree< T >::treeHeight () const [inline]
Find the height of the tree. Arguments: none
Returns:
(int) the height of the tree.
Returns the Height of the tree
Definition at line 336 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::height(), and SimpleBinaryTree< T >::root.
{
        return height(root);
}
template<class T> int SimpleBinaryTree< T >::treeNodeCount () const [inline]
Find the number of nodes in the tree. Arguments: none
Returns:
(int) the number of nodes.
Returns the number of nodes in the tree
Definition at line 352 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::nodeCount(), and SimpleBinaryTree< T >::root.
{
        return nodeCount(root);
}
template<class T> int SimpleBinaryTree< T >::treeLeavesCount () const [inline]
Find the number of leaves in the tree. Arguments: none
Returns:
(int) the number of leaves.
Returns the number of leaves in the tree
Definition at line 370 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::leavesCount(), and SimpleBinaryTree< T >::root.
{
        return leavesCount(root);
}
template<class T> void SimpleBinaryTree< T >::destroyTree () [inline]
Destroy the binary tree.
Definition at line 540 of file SimpleBinaryTree.h.
References SimpleBinaryTree< T >::destroy(), and SimpleBinaryTree< T >::root.
Referenced by LibSystem::init().
{
        destroy(root);
}
template<class T> virtual bool SimpleBinaryTree< T >::searchByKey (const long & searchKey) const [pure virtual]
Implemented in BinarySearchTree< T >, BinarySearchTree< BookLoan >, and BinarySearchTree< BookType >.
template<class T> virtual bool SimpleBinaryTree< T >::search (const T & searchItem) const [pure virtual]
Implemented in BinarySearchTree< T >, BinarySearchTree< BookLoan >, and BinarySearchTree< BookType >.
template<class T> virtual void SimpleBinaryTree< T >::insert (const T & insertItem) [pure virtual]
Implemented in BinarySearchTree< T >, BinarySearchTree< BookLoan >, and BinarySearchTree< BookType >.
template<class T> virtual void SimpleBinaryTree< T >::deleteNode (const T & deleteItem) [pure virtual]
Implemented in BinarySearchTree< T >, BinarySearchTree< BookLoan >, and BinarySearchTree< BookType >.
template<class T> void SimpleBinaryTree< T >::copyTree (nodeType< T > *& copiedTreeRoot, nodeType< T > * otherTreeRoot) [inline, private]
Copy from otherTreeRoot into copiedTreeRoot. Arguments: Reference to a nodeType<T> *, nodeType<T> *
Parameters:
copiedTreeRoot (nodeType<T> *&) The current node of the tree we are building.
otherTreeRoot (nodeType<T> *) The current node of the tree we are copying from.
Allocates new nodeTypes on the heap.
Copy from otherTreeRoot into copiedTreeRoot.
Allocates new nodeTypes on the heap.
Definition at line 490 of file SimpleBinaryTree.h.
References nodeType< T >::data, nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::operator=(), and SimpleBinaryTree< T >::SimpleBinaryTree().
{
        if (otherTreeRoot == 0)
                copiedTreeRoot = 0;
        else
        {
                copiedTreeRoot = new nodeType<T>;
                copiedTreeRoot->data = otherTreeRoot->data;
                copyTree(copiedTreeRoot->left, otherTreeRoot->left);
                copyTree(copiedTreeRoot->right, otherTreeRoot->right);
        }
}
template<class T> void SimpleBinaryTree< T >::destroy (nodeType< T > *& p) [inline, private]
Deallocates each node.
Sets p = NULL.
Destroy the given node and its children. Arguments: Reference to a nodeType<T>*
Parameters:
p (nodeType<T> *) The root node of the current sub-tree.
To destroy a binary tree, for each node we destroy its left subtree, then its right subtree. Then deallocate the node itself.
To destroy a binary tree, for each node we destroy its left subtree, then its right subtree. Then deallocate the node itself.
Definition at line 522 of file SimpleBinaryTree.h.
References nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::destroyTree(), SimpleBinaryTree< T >::operator=(), and SimpleBinaryTree< T >::~SimpleBinaryTree().
{
        if (p != 0)
        {
                destroy(p->left);
                destroy(p->right);
                delete p;
                p = 0;
        }
}
template<class T> void SimpleBinaryTree< T >::inOrder (nodeType< T > * p) const [inline, private]
Perform an in-order traversal, printing each node (nodeType<T>). Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) the root of the current sub-tree being traversed.
Perform an in-order traversal, printing each node.
Definition at line 596 of file SimpleBinaryTree.h.
References nodeType< T >::data, nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::inOrderTraversal().
{
        if (p != 0)
        {
                inOrder(p->left);
                cout << p->data << " ";  // process me in the middle.
                inOrder(p->right);
        }
}
template<class T> void SimpleBinaryTree< T >::preOrder (nodeType< T > * p) const [inline, private]
Perform a pre-order traversal, printing each node (nodeType<T>). Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) the root of the current sub-tree being traversed.
Perform a pre-order traversal, print each node.
Definition at line 615 of file SimpleBinaryTree.h.
References nodeType< T >::data, nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::preOrderTraversal().
{
        if (p != NULL)
        {
                cout << p->data << " ";  // process me first
                preOrder(p->left);
                preOrder(p->right);
        }
}
template<class T> void SimpleBinaryTree< T >::postOrder (nodeType< T > * p) const [inline, private]
Perform a post-order traversal, printing each node (nodeType<T>). Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) the root of the current sub-tree being traversed.
Perform a post-order traversal, print each node.
Definition at line 635 of file SimpleBinaryTree.h.
References nodeType< T >::data, nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::postOrderTraversal().
{
        if (p != NULL)
        {
                postOrder(p->left);
                postOrder(p->right);
                cout << p->data << " "; // process me last
        }
}
template<class T> int SimpleBinaryTree< T >::height (nodeType< T > * p) const [inline, private]
Find the height of the tree pointed to by p. Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) the root node of the current sub-tree.
Returns:
(int) the height of the tree.
Return the height of the tree pointed to by p
Definition at line 391 of file SimpleBinaryTree.h.
References nodeType< T >::left, SimpleBinaryTree< T >::max(), and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::treeHeight().
{
        if (p == 0)
                return 0;
        else
                return 1 + max(height(p->left), height(p->right));
}
template<class T> int SimpleBinaryTree< T >::max (const int & x, const int & y) const [inline, private]
Find the greater of x and y. Arguments: int, int
Parameters:
x (int) An int value.
y (int) An int value.
Returns:
(int) the greater of (x , y)
Used to find the height of a tree.
Return the greater of (x , y)
Definition at line 416 of file SimpleBinaryTree.h.
Referenced by SimpleBinaryTree< T >::height().
{
        if (x >= y)
        {
                return x;
        }
        else
        {
                return y;
        }
}
template<class T> int SimpleBinaryTree< T >::nodeCount (nodeType< T > * p) const [inline, private]
Returns the number of nodes in the binary tree to which p points. Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) The root node of the current sub-tree
Returns:
(int) the number of (NON-NULL) nodes in the tree.
Returns the number of nodes in the binary tree to which p points.
Definition at line 439 of file SimpleBinaryTree.h.
References nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::treeNodeCount().
{
        if (p != 0)
        {
                return(
                                          1
                                        + nodeCount(p->left)
                                        + nodeCount(p->right)
                           );
        }
        return 0;
}
template<class T> int SimpleBinaryTree< T >::leavesCount (nodeType< T > * p) const [inline, private]
Returns the number of leaves in the binary tree to which p points. Arguments: nodeType<T> *
Parameters:
p (nodeType<T> *) The root node of the current sub-tree
Returns:
(int) the number of leaves in the tree.
Returns the number of leaves in the binary tree to which p points.
Definition at line 464 of file SimpleBinaryTree.h.
References nodeType< T >::left, and nodeType< T >::right.
Referenced by SimpleBinaryTree< T >::treeLeavesCount().
{
        if (p == 0)
        {
                // This is a leaf node
                return 1;
        }
        // This is NOT a leaf node.
        return( leavesCount(p->left) + leavesCount(p->right) );
}
Member Data Documentation
template<class T> nodeType<T>* SimpleBinaryTree< T >::root [protected]
Definition at line 148 of file SimpleBinaryTree.h.
Referenced by BinarySearchTree< T >::deleteNode(), SimpleBinaryTree< T >::destroyTree(), BinarySearchTree< T >::getNodeValue(), BinarySearchTree< T >::inOrderDump(), SimpleBinaryTree< T >::inOrderTraversal(), BinarySearchTree< T >::insert(), SimpleBinaryTree< T >::isEmpty(), SimpleBinaryTree< T >::operator=(), BinarySearchTree< T >::postOrderDump(), SimpleBinaryTree< T >::postOrderTraversal(), BinarySearchTree< T >::preOrderDump(), SimpleBinaryTree< T >::preOrderTraversal(), BinarySearchTree< T >::replaceNode(), BinarySearchTree< T >::search(), BinarySearchTree< T >::searchByKey(), SimpleBinaryTree< T >::SimpleBinaryTree(), SimpleBinaryTree< T >::treeHeight(), SimpleBinaryTree< T >::treeLeavesCount(), SimpleBinaryTree< T >::treeNodeCount(), and SimpleBinaryTree< T >::~SimpleBinaryTree().
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/SimpleBinaryTree.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/SimpleBinaryTree.cpp