Library System: MemberType Class Reference
MemberType Class Reference
Stores information about a user (staff / patron) of the Library System.
#include <MemberType.h>
Public Member Functions
MemberType ()
Default Constructor.
.
~MemberType ()
Destructor.
.
MemberType (const MemberType &b)
Copy constructor.
.
const MemberType & operator= (const MemberType &otherMember)
Assignment op override.
.
bool operator== (const MemberType &otherMember) const
Equality Comparison operator override.
.
void setFirstName (const string &s)
Set the first name of this Member.
.
void setLastName (const string &s)
Set the last name of this Member.
.
void setUserId (const long &l)
Set the user ID of this Member.
.
void setAuthority (const string &s)
Set whether this Member is staff or a patron of the Library.
.
void getFirstName (string &s) const
Get the first name of this member.
.
void getLastName (string &s) const
Get the last name of this member.
.
void getUserId (long &l) const
Get the user ID of this member.
.
void getAuthority (string &s) const
Get whether this Member is staff or a patron of the Library.
.
Private Member Functions
void Reset ()
Reset method.
.
void Copy (const MemberType &b)
Copy method.
.
Private Attributes
string firstName
First name of the member.
.
string lastName
Last name of the member.
.
long userId
User ID of the member.
.
string authorityLevel
"staff" or "patron".
Detailed Description
Definition at line 24 of file MemberType.h.
Constructor & Destructor Documentation
MemberType::MemberType ()
Constructor (default). Arguments: none
Definition at line 28 of file MemberType.cpp.
References Reset().
{
        Reset();
}
MemberType::~MemberType ()
Destructor. Arguments: none.
Definition at line 41 of file MemberType.cpp.
{
}
MemberType::MemberType (const MemberType & otherMember)
Copy constructor. Arguments: MemberType
Parameters:
otherMember (MemberType) The member object we are copying from.
Definition at line 56 of file MemberType.cpp.
References Copy(), and Reset().
{
        Reset();
        Copy(otherMember);
}
Member Function Documentation
const MemberType & MemberType::operator= (const MemberType & otherMember)
Assignment operator override.. Arguments: MemberType
Parameters:
otherMember (MemberType) The user object we are copying from.
Returns:
MemberType The value of the current object (*this)
Checks to avoid self-assignment.
Definition at line 75 of file MemberType.cpp.
References Copy().
{
        // Avoid self-assignment
        if (this != &otherMember)
        {
                Copy(otherMember);
        }
        return *this; // The value of the object that was just assigned.
}
bool MemberType::operator== (const MemberType & otherMember) const
Equality comparison operator override.. Arguments: MemberType
Parameters:
otherMember (MemberType) The member object we are comparing against.
Returns:
bool True if the given object matches this object.
Definition at line 97 of file MemberType.cpp.
References getAuthority(), getFirstName(), getLastName(), and getUserId().
{
        // Checking against self ?
        // This is an address comparison (i think)  OTHERWISE it will be infinite recursion.  AAA!
        if (this != &otherMember)
        {
                // This MemberType
                string myFirstName              = "none";
                string myLastName               = "none";
                long myUserId                   = 0;
                string myAuthorityLevel = "patron";
                getFirstName    (myFirstName);
                getLastName             (myLastName);
                getUserId               (myUserId);
                getAuthority    (myAuthorityLevel);
                // Other MemberType
                string otherFirstName           = "none";
                string otherLastName            = "none";
                long otherUserId                        = 0;
                string otherAuthorityLevel      = "patron";
                otherMember.getFirstName        (otherFirstName);
                otherMember.getLastName         (otherLastName);
                otherMember.getUserId           (otherUserId);
                otherMember.getAuthority        (otherAuthorityLevel);
                // Equality comparison happens here.
                if      (
                        myFirstName                     == otherFirstName               &&
                        myLastName                      == otherLastName                &&
                        myUserId                        == otherUserId                  &&
                        myAuthorityLevel        == otherAuthorityLevel
                        )
                {
                        return true;    // Everything matches exactly. Equal.
                }
                return false;           // Members do not match exactly.  Inequal.
        }
        else
        {
                return true; // this == this.  So they are equal.
        }
}
void MemberType::setFirstName (const string & s)
Set the first name of this user. Arguments: string
Parameters:
s (string)
Definition at line 167 of file MemberType.cpp.
References firstName.
Referenced by Copy(), MembersLoader::LoadUsers(), and LibSystem::staffAddPatrons().
{
        firstName = s;
}
void MemberType::setLastName (const string & s)
Set the last name of this user. Arguments: string
Parameters:
s (string)
Definition at line 179 of file MemberType.cpp.
References lastName.
Referenced by Copy(), MembersLoader::LoadUsers(), and LibSystem::staffAddPatrons().
{
        lastName = s;
}
void MemberType::setUserId (const long & l)
Set the ID of this user. Arguments: long
Parameters:
l (long)
Definition at line 194 of file MemberType.cpp.
References userId.
Referenced by Copy(), MembersLoader::LoadUsers(), and LibSystem::staffAddPatrons().
{
        userId = l;
}
void MemberType::setAuthority (const string & s)
Set whether this user is "staff" or "patron" Arguments: string
Parameters:
s (string)
Definition at line 208 of file MemberType.cpp.
References authorityLevel.
Referenced by Copy(), MembersLoader::LoadUsers(), and LibSystem::staffAddPatrons().
{
        authorityLevel = s;
}
void MemberType::getFirstName (string & s) const
Get the first name of this user. Arguments: string
Parameters:
s (string)
Definition at line 230 of file MemberType.cpp.
References firstName.
Referenced by Copy(), LibSystem::displayAllUsers(), operator==(), MembersLoader::SaveUsers(), and LibSystem::waitForLogin().
{
        s = firstName;
}
void MemberType::getLastName (string & s) const
Get the last name of this user. Arguments: string
Parameters:
s (string)
Definition at line 242 of file MemberType.cpp.
References lastName.
Referenced by Copy(), LibSystem::displayAllUsers(), operator==(), MembersLoader::SaveUsers(), and LibSystem::waitForLogin().
{
        s = lastName;
}
void MemberType::getUserId (long & l) const
Get the ID of this user. Arguments: long
Parameters:
l (long) Receives the User ID of this user.
Definition at line 255 of file MemberType.cpp.
References userId.
Referenced by Copy(), LibSystem::displayAllUsers(), operator==(), LibSystem::promptBorrowBook(), LibSystem::promptReturnBook(), LibSystem::renewBook(), MembersLoader::SaveUsers(), LibSystem::showLoansForCurrentUser(), LibSystem::userExists(), and LibSystem::waitForLogin().
{
        l = userId;
}
void MemberType::getAuthority (string & s) const
Get whether this user is "staff" or "patron". Arguments: string
Parameters:
s (string) Receives the data.
Definition at line 268 of file MemberType.cpp.
References authorityLevel.
Referenced by Copy(), LibSystem::displayAllUsers(), operator==(), MembersLoader::SaveUsers(), and LibSystem::waitForLogin().
{
        s = authorityLevel;
}
void MemberType::Reset () [private]
Reset method. Arguments: none
Definition at line 285 of file MemberType.cpp.
References authorityLevel, firstName, lastName, and userId.
Referenced by MemberType().
{
        firstName               = "none";
        lastName                = "none";
        userId                  = 0;            // User cannot use the system
        authorityLevel  = "patron";
}
void MemberType::Copy (const MemberType & otherMember) [private]
Copy method. Arguments: MemberType
Parameters:
otherMember (MemberType) The user object we are copying from
Definition at line 304 of file MemberType.cpp.
References getAuthority(), getFirstName(), getLastName(), getUserId(), setAuthority(), setFirstName(), setLastName(), and setUserId().
Referenced by MemberType(), and operator=().
{
        // Other MemberType
        string otherFirstName           = "none";
        string otherLastName            = "none";
        long otherUserId                        = 0;
        string otherAuthorityLevel      = "patron";
        // Get properties of other member
        otherMember.getFirstName        (otherFirstName);
        otherMember.getLastName         (otherLastName);
        otherMember.getUserId           (otherUserId);
        otherMember.getAuthority        (otherAuthorityLevel);
        // Set my properties
        setFirstName    (otherFirstName);
        setLastName             (otherLastName);
        setUserId               (otherUserId);
        setAuthority    (otherAuthorityLevel);
}
Member Data Documentation
string MemberType::firstName [private]
Definition at line 138 of file MemberType.h.
Referenced by getFirstName(), Reset(), and setFirstName().
string MemberType::lastName [private]
Definition at line 144 of file MemberType.h.
Referenced by getLastName(), Reset(), and setLastName().
long MemberType::userId [private]
Definition at line 150 of file MemberType.h.
Referenced by getUserId(), Reset(), and setUserId().
string MemberType::authorityLevel [private]
Definition at line 156 of file MemberType.h.
Referenced by getAuthority(), Reset(), and setAuthority().
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/MemberType.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/MemberType.cpp