Library System: DataManip Class Reference
DataManip Class Reference
Has some static helper methods for removing white space from strings.
#include <DataManip.h>
Public Member Functions
DataManip ()
Default Constructor.
.
Static Public Member Functions
static void removeLeadingWhiteSpace (string &inStr)
Remove leading white space from the given string.
.
static void removeTrailingWhiteSpace (string &inStr)
Remove trailing white space from the given string.
.
Detailed Description
Definition at line 26 of file DataManip.h.
Constructor & Destructor Documentation
DataManip::DataManip ()
Default Constructor
Definition at line 26 of file DataManip.cpp.
{
}
Member Function Documentation
void DataManip::removeLeadingWhiteSpace (string & inStr) [static]
Helper method
Definition at line 36 of file DataManip.cpp.
Referenced by BooksLoader::LoadLibraryBooks(), and MembersLoader::LoadUsers().
{
        // Remove leading whitespaces.
        size_t pos;
        pos = inStr.find_first_not_of(" \t\f\v\n\r");
        inStr = inStr.substr(pos);    // get the string after that position.
}
void DataManip::removeTrailingWhiteSpace (string & inStr) [static]
Helper method
Definition at line 51 of file DataManip.cpp.
Referenced by BooksLoader::LoadLibraryBooks(), and MembersLoader::LoadUsers().
{
        // Erase trailing whitespaces.
        string whitespaces (" \t\f\v\n\r");
        size_t found;
        found = inStr.find_last_not_of(whitespaces);
        if (found != string::npos)
                inStr.erase(found + 1);
        else
                inStr.clear();            // inStr is all whitespace
}
The documentation for this class was generated from the following files:
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/h/DataManip.h
C:/Users/Mike/Dropbox/uni/ict209/assignment 2/assignmentTwo/LibrarySystem/source/DataManip.cpp